### ISSUE TITLE
Hello, and a few questions

### ISSUE THREAD

**Issue by TripleCamera** [MeterPreter57/MeterPreter57.github.io#1]
Hello, I am interested in this project. May I ask that where the code comes from? Besides, is it possible to add progress saving and multiplayer just like the official version?

**Comment by MeterPreter57** [comment]
Hi, all files come from https://minidayz.com/play/sp/ it is possible to download multiplayer version https://minidayz.com/play/mp/ however I don't know how to enable progress saving or multiplayer without login.

**Comment by TripleCamera** [comment]
Hi, I tried the official version. Although I created an account, it says "Login error. Please try again." Is this my problem or the server's problem? Why can I play freely on your site without login?
![minidayz_loginerror](https://user-images.githubusercontent.com/66164427/197403458-bed29dce-6e9e-46f7-a54b-d5896e6b0a33.png)

**Comment by MeterPreter57** [comment]
Browser version is no longer supported https://minidayz.com/blog/mini-dayz-browser-version-will-no-longer-be-supported
You can play here because when you launch the game login page is skipped.

**Comment by TripleCamera** [comment]
Wow that's great!

By the way, how did you download all the resources? I tried a browser extension called "Save All Resources" but only got some of the files you got.

**Comment by MeterPreter57** [comment]
This is a list of all files https://minidayz.com/play/sp/offline.js then I used "WGET" to download everything

**Comment by TripleCamera** [comment]
> This is a list of all files https://minidayz.com/play/sp/offline.js then I used "WGET" to download everything

Great! I tried `wget` and solved problems by searching, now it works fine for me.

**Comment by TripleCamera** [comment]
Hi, I was studying about skipping login. Then I noticed that in `data.js`, you changed `Login` to `Menu`, may I ask why?

**Comment by MeterPreter57** [comment]
In original mini dayz "Login" is the first layout (layout is like a scene in unity). I changed it to "Menu", so when the game is launched main menu is shown instead of login page

**Comment by TripleCamera** [comment]
> In original mini dayz "Login" is the first layout (layout is like a scene in unity). I changed it to "Menu", so when the game is launched main menu is shown instead of login page

That's so technical! By the way, do you have some sort of chat group for this?

**Comment by MeterPreter57** [comment]
No I don't have a chat group

**Comment by TripleCamera** [comment]
> No I don't have a chat group

What about instant messaging apps, like Discord?

**Comment by TripleCamera** [comment]
Yes please :yum:

**Comment by MeterPreter57** [comment]
RedAndWhite#7723

**Comment by W84Soft** [comment]
Hi,
I created a pull request with a working server for saving and loading game progress.
To run this server you need to install NodeJS first and all node_modules.
I'm currently working on a working multiplayer server, I think I'm on the right track :)

**Comment by W84Soft** [comment]
![Uploading Screenshot 2024-04-13 at 22-52-26 MINIDAYZ.png…]()

**Comment by W84Soft** [comment]
![Screenshot 2024-04-13 at 22-52-26 MINIDAYZ](https://github.com/MeterPreter57/MeterPreter57.github.io/assets/53473441/d95c7a23-ea95-4278-aa0a-b1922969add3)

**Comment by TripleCamera** [comment]
Wow, it's been a year.

@W84Soft Thanks for the work! Sorry that I can't offer any help.

I remember that at that time, I was studying about different mods for Mini DayZ mobile, and I made [a list](https://docs.google.com/spreadsheets/d/16F1_WNt-zCrhYcDgB4SEBw7N7iv0eDGqxqW9i0Z5wJk/edit?usp=sharing). Besides, I tried to find a map that was lost on the Internet. But later on, I was busy and dropped this project. :frowning_face:

Now seems that @MeterPreter57 found the missing map (`map_narva.jpg`, is this the original version?) and uploaded it last year. I am pretty surprised. Please tell us how you did that! :yum:

**Comment by W84Soft** [comment]
This is very difficult to explain, I used all possible browser tools to find out what data the game requires. I looked through the network traffic, added console.logs to the code to check what function was responsible for what, I used js beuitifier to make data.js more readable and I looked for key words that related to POST requests like /sp_save, after receiving the data I saved it to the variable, later, when the game asked for data, I provided them. All through trial and error.
If you want, I can make a version that can be run on Windows or Linux using ElectronJS without the need to install nodeJS :)

**Comment by MeterPreter57** [comment]
I actually tried to do something like this but failed. Cool that you managed to do that. Looks like you already have original files for hosting a server. Do you use the Windows version because the Linux version just segfaults for me?

**Comment by W84Soft** [comment]
Actually I use all operating systems, windows, linux, macos and they all work for me. I also bought some computers to test applications written in ElectronJS, so I think that if I also create a version for PC, it would work without any problems.

**Comment by MeterPreter57** [comment]
I probably downloaded wrong files can you share your?

**Comment by W84Soft** [comment]
I created pull request with server response simulator and localStorage solution for storing data :)

**Comment by MeterPreter57** [comment]
Thanks, works great!

**Comment by W84Soft** [comment]
@MeterPreter57, can you add me as collaborator in "minidayz-multiplayer" repository? 😄

**Comment by MeterPreter57** [comment]
I've invited you

**Comment by MeterPreter57** [comment]
> windows, linux, macOS and they all work for me

@W84Soft, the [official website](https://minidayz.com/servers) says "It is currently not possible to host servers on a system running OSX." Just to be sure, are we talking about the same server files?

**Comment by W84Soft** [comment]
Oh, sorry, there was a slight misunderstanding, I'm working on recreating the multiplayer in nodeJS from scratch to make it work multiplatform, I thought you wrote about singleplayer for Windows, Linux and Macos based on ElectronJS

**Comment by W84Soft** [comment]
@MeterPreter57 Could you share the server files from the original site?

**Comment by MeterPreter57** [comment]
Sure, however please note that I didn't download these files from the official website. I got them from a person a year or two ago. And I can't be sure that they are safe to run because the source is unknown. I suggest using WM for testing. I will upload them to the cloud and share the link here

**Comment by W84Soft** [comment]
Thanks, this can be very helpful in creating own and safe server solution. 😄

**Comment by MeterPreter57** [comment]
https://mega.nz/file/pvEB1KIQ#jJI5Myq05oYEUgLBe1B58FzsVu8ZfGwi3cGfnUBLa10

**Comment by W84Soft** [comment]
After some modifications original server files worked well on macos 😄 
<img width="865" alt="Zrzut ekranu 2024-04-14 o 22 41 37" src="https://github.com/MeterPreter57/MeterPreter57.github.io/assets/53473441/97fa2d96-0c95-406c-ba40-ee843853b7ce">

**Comment by TripleCamera** [comment]
> After some modifications original server files worked well on macos 😄

That is very exciting news. Thanks for your hard work!

By the way, @MeterPreter57 may I ask how you found the lost `map_narva.jpg`? Is it the original file from dayz.com or is it compressed? I noticed that this is a JPEG file, while `map_minidayz.png` is a PNG file.

**Comment by MeterPreter57** [comment]
I’m not sure. Probably a lucky google search or somebody sent it to me

**Comment by TripleCamera** [comment]
> I’m not sure. Probably a lucky google search or somebody sent it to me

I compared Google results and your version of `map_minidayz.png`. It seems that Google results are an older revision of the map. Now I suspect that `map_narva.png` is not the original version.

I have search both the [Wayback Machine](https://web.archive.org/) and [archive.today](https://archive.today/). They don't have an archive for the maps ([`map_minidayz.png`](http://dayz.com/assets/img/minidayz/map_minidayz.png) and [`map_narva.png`](https://dayz.com/assets/img/minidayz/map_narva.png)).

Mini DayZ has a Discord server, maybe we can ask there.

**Comment by MeterPreter57** [comment]
While my friend and I were playing, the map was pretty accurate although we hadn't visited all the places. We can try to ask but It's been around five years since the game met its end of life so I doubt that we will find someone with the latest copy.

**Comment by W84Soft** [comment]
❤️ 
![obraz](https://github.com/MeterPreter57/MeterPreter57.github.io/assets/53473441/75f9e2da-8bb2-4cf9-ba7b-b9290d2ba653)

**Comment by MeterPreter57** [comment]
📈📈📈
![image](https://github.com/MeterPreter57/MeterPreter57.github.io/assets/57488277/e84be873-3f04-4013-ba7c-156191e9222f)

**Comment by MeterPreter57** [comment]
The only way to "update" the game is to delete the data of the page. Is this correct?

**Comment by W84Soft** [comment]
Yes, you need to clear the website data or run the game in incognito mode

**Comment by MeterPreter57** [comment]
Is there a way to substitute images with current mods functionality? I tried registering a service worker with no luck

**Comment by W84Soft** [comment]
I created a pull request with mod caching 😄

**Comment by W84Soft** [comment]
@MeterPreter57 
I have a suggestion.
Can you rename the repository to Mini DAYZ PC?
We will generate the link to the gameplay via https://raw.githack.com/ instead of github.io, this will make it easier for people to find this repository on Google 😄

**Comment by W84Soft** [comment]
As for the multiplayer version, I'm still working on it in my free time, I'll share something soon, but at the moment I'm trying to understand Peer to Peer connections and why they don't work for me

**Comment by MeterPreter57** [comment]
@W84Soft I never used githack.com but I guess this is possible. Everybody who has the link to the repo will lose it and their saves if they have not exported them. We also should post new link in discord and facebook so that people can find this repo again.

**Comment by American1944** [comment]
Hello. I know you guys are clearly still working on the project. And its amazing you guys are still working on a game thats been abandoned by the developers. I just wanted to ask whether you guys still are working on multiplayer and whether we can see a playable multiplayer. @W84Soft is the server files working and can I have them to play with a friend?

**Comment by W84Soft** [comment]
Hi, unfortunately multiplayer is still unplayable, I managed to display the server list and run the original room creation files, but it's very difficult to join a room and I haven't had time to try to fix it lately.

Once I manage to fix everything I'll let you know :)

**Comment by W84Soft** [comment]
@MeterPreter57 Could you change the repository name to: MiniDayZ-PC, I sent a pull request which uses githack to serve the game 😄

**Comment by dayzblack** [comment]
hello,l found some bugs when playing minidayz,but l can't typecode and can't fix these bugs. lf these is a kind person who can help fix the bug, thank you! when playing these will be such a situation that zombies will suddenly move next to you when you run in front, and when you meet hostile survivors, you hide in the house and he will attack you through the wall. ls there any kind person who can help fix this bug.

**Comment by W84Soft** [comment]
@dayzblack Unfortunately fixing these bugs is too complicated because it is the core of the game engine, probably fixing these bugs would require modifying the collision logic of entire maps and NPC logic.

**Comment by W84Soft** [comment]
@MeterPreter57 check my latest pull request.

**Comment by MeterPreter57** [comment]
Merged. Save editor looks great 👍

**Comment by MeterPreter57** [comment]
I looked into minidayz "code" a few month ago. I was mostly interested in adding new items. However I saw other parts too.

 > zombies will suddenly move next to you when you run in front

 I think you are talking about strange movement around corners. Probably nothing we can do.

 > when you meet hostile survivors, you hide in the house and he will attack you through the wall

Well minidayz had similar problem with one of the buildings that was fixed in + version. I don't know how but we can try to make all walls thicker. This should be possible but I'm not sure if this will help.

**Comment by W84Soft** [comment]
@MeterPreter57 @TripleCamera @American1944 @dayzblack

Please check if the multiplayer version works for you, there are files to create a server in the server-files directory

I don't know why but I can't fix anything regarding connections, it may be the fault of my internet provider who may be blocking RTC connections, but to be sure I need you to test if it works for you

Here is repository:
### https://github.com/MeterPreter57/minidayz-multiplayer
[![PC MiniDayZ Multiplayer](https://github.com/user-attachments/assets/374d7040-cdcd-4d37-944d-a87a6b31f4fb)](https://github.com/MeterPreter57/minidayz-multiplayer)

**Comment by MeterPreter57** [comment]
@W84Soft So I tested it. Looks like I can connect to the server but can't enter the game.
I tried to start a server on linux with no luck. However, the Windows version seems to work fine. I'm stuck on the loading screen and get a few errors in the console. But I can send a message in the chat that the server will receive and I can see from another device that the server is not empty.
I get this on both my devices.
```
Access to fetch at 'https://oauth.bistudio.com/api/user/app/SPROCKET2DAYZMINI001/saved-game/8753451o5w57g83b6a8b_Chernarus_plus?access_token=token_user&client_id=C7VX&client_secret=$2a$05$VQ7yekWgQLBcm/H6egbpuu&key=GAUP' from origin 'https://raw.githack.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
The FetchEvent for "https://oauth.bistudio.com/api/user/app/SPROCKET2DAYZMINI001/saved-game/8753451o5w57g83b6a8b_Chernarus_plus?access_token=token_user&client_id=C7VX&client_secret=$2a$05$VQ7yekWgQLBcm/H6egbpuu&key=GAUP" resulted in a network error response: the promise was rejected.
Promise.then
(anonymous) @ sw.js:333
sw.js:289 
```
This I get only on my laptop on windows in edge
```
        Uncaught (in promise) TypeError: Failed to fetch
    at sw.js:289:11
(anonymous) @ sw.js:289
mp-server-simulator.js:39 
        
        
        GET https://oauth.bistudio.com/api/user/app/SPROCKET2DAYZMINI001/saved-game/8753451o5w57g83b6a8b_Chernarus_plus?access_token=token_user&client_id=C7VX&client_secret=$2a$05$VQ7yekWgQLBcm/H6egbpuu&key=GAUP net::ERR_FAILED
send @ mp-server-simulator.js:39
instanceProto.doRequest @ c2runtime.js:15555
Acts.Request @ c2runtime.js:15607
Action.run_object @ c2runtime.js:10892
EventBlock.run_actions_and_subevents @ c2runtime.js:10367
EventBlock.run @ c2runtime.js:10340
Runtime.executeSingleTrigger @ c2runtime.js:6762
Runtime.triggerOnSheetForTypeName @ c2runtime.js:6709
Runtime.triggerOnSheet @ c2runtime.js:6662
Runtime.trigger @ c2runtime.js:6646
mp.onpeermessage @ c2runtime.js:22418
Peer.doOnMessage @ c2mp-peer.js:728
Peer.onMessage @ c2mp-peer.js:633
dc.onmessage @ c2mp-peer.js:102
mp-server-simulator.js:39 

        Uncaught (in promise) TypeError: Failed to fetch
    at window.XMLHttpRequest.send (mp-server-simulator.js:39:62)
    at instanceProto.doRequest (c2runtime.js:15555:13)
    at Acts.Request (c2runtime.js:15607:9)
    at Action.run_object (c2runtime.js:10892:10)
    at EventBlock.run_actions_and_subevents (c2runtime.js:10367:38)
    at EventBlock.run (c2runtime.js:10340:9)
    at Runtime.executeSingleTrigger (c2runtime.js:6762:10)
    at Runtime.triggerOnSheetForTypeName (c2runtime.js:6709:16)
    at Runtime.triggerOnSheet (c2runtime.js:6662:13)
    at Runtime.trigger (c2runtime.js:6646:12)
send @ mp-server-simulator.js:39
instanceProto.doRequest @ c2runtime.js:15555
Acts.Request @ c2runtime.js:15607
Action.run_object @ c2runtime.js:10892
EventBlock.run_actions_and_subevents @ c2runtime.js:10367
EventBlock.run @ c2runtime.js:10340
Runtime.executeSingleTrigger @ c2runtime.js:6762
Runtime.triggerOnSheetForTypeName @ c2runtime.js:6709
Runtime.triggerOnSheet @ c2runtime.js:6662
Runtime.trigger @ c2runtime.js:6646
mp.onpeermessage @ c2runtime.js:22418
Peer.doOnMessage @ c2mp-peer.js:728
Peer.onMessage @ c2mp-peer.js:633
dc.onmessage @ c2mp-peer.js:102
Promise.then
send @ mp-server-simulator.js:39
instanceProto.doRequest @ c2runtime.js:15555
Acts.Request @ c2runtime.js:15607
Action.run_object @ c2runtime.js:10892
EventBlock.run_actions_and_subevents @ c2runtime.js:10367
EventBlock.run @ c2runtime.js:10340
Runtime.executeSingleTrigger @ c2runtime.js:6762
Runtime.triggerOnSheetForTypeName @ c2runtime.js:6709
Runtime.triggerOnSheet @ c2runtime.js:6662
Runtime.trigger @ c2runtime.js:6646
mp.onpeermessage @ c2runtime.js:22418
Peer.doOnMessage @ c2mp-peer.js:728
Peer.onMessage @ c2mp-peer.js:633
dc.onmessage @ c2mp-peer.js:102
mods.js:228 Registered service worker on https://raw.githack.com/MeterPreter57/minidayz-multiplayer/main/client/
```

**Comment by W84Soft** [comment]
@MeterPreter57 @TripleCamera @American1944 @dayzblack 
### I finally managed to fix MiniDayZ multiplayer!

<img width="1440" alt="MiniDayZMP" src="https://github.com/user-attachments/assets/062d8052-f9d3-411f-8000-25f792aaa84b" />

### Here is repository:
https://github.com/MeterPreter57/minidayz-multiplayer

[![PC MiniDayZ Multiplayer](https://github.com/user-attachments/assets/374d7040-cdcd-4d37-944d-a87a6b31f4fb)](https://github.com/MeterPreter57/minidayz-multiplayer)

**Comment by MeterPreter57** [comment]
Great job! After all these years I'm going to invite my friends to play. 
I tested it. It's hard to even enter a building, most likely my internet is to blame. Is there anything that can help? Maybe a server in close proximity to everybody?

**Comment by W84Soft** [comment]
The best situation is when everyone has good internet or when the friend with the fastest internet hosts the game.

**Comment by AlphaSystemsPL** [comment]
Hey @MeterPreter57, I have plans to add some interesting modifications, adding new items to the game and maybe even new mobs, but I need more permissions as a contributor to the repository so that if I leave bugs in the repository I can react quickly to fix the bug, without having to create a pull request.

Could you do this for me? I would be grateful 😄

**Comment by MeterPreter57** [comment]
@W84Soft Sure
